spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true # 테스트 코드의 실제 실행되는 쿼리가 log로 남는다.
    properties:
      hibernate:
        format_sql: true # hibernate에서 실행되는 쿼리가 log로 남는다.
    generate-ddl: false # 구현체와 상관없이 자동으로 ddl을 만든다.
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/book_manager
    username: root
    password: 1234
    initialization-mode: always
server:
  port: 8070
